### ISSUE TITLE
rg.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

### ISSUE THREAD

**Issue by archenroot** [vojtechruz/jsonb-hibernate-example#1]
I added into application.properties following lines as soon as otherwise the app expects database to exists:
```
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
```

So I have auto created Person table in database. Now the test is failing:
```
2017-09-06 15:41:43.437  INFO 13787 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.0.12.Final}
2017-09-06 15:41:43.439  INFO 13787 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2017-09-06 15:41:43.440  INFO 13787 --- [           main] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist
2017-09-06 15:41:43.474  INFO 13787 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2017-09-06 15:41:43.749  INFO 13787 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: com.vojtechruzicka.hibernate.CustomPostgreSqlDialect
2017-09-06 15:41:43.852  INFO 13787 --- [           main] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2017-09-06 15:41:43.853  INFO 13787 --- [           main] org.hibernate.type.BasicTypeRegistry     : HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@7965a51c
2017-09-06 15:41:43.966  WARN 13787 --- [           main] org.hibernate.orm.deprecation            : HHH90000014: Found use of deprecated [org.hibernate.id.SequenceGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.
2017-09-06 15:41:44.141  INFO 13787 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000227: Running hbm2ddl schema export
Hibernate: drop table if exists person cascade
Hibernate: drop sequence hibernate_sequence
2017-09-06 15:41:44.147 ERROR 13787 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000389: Unsuccessful: drop sequence hibernate_sequence
2017-09-06 15:41:44.147 ERROR 13787 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : ERROR: must be owner of relation hibernate_sequence
Hibernate: create sequence hibernate_sequence start 1 increment 1
2017-09-06 15:41:44.148 ERROR 13787 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000389: Unsuccessful: create sequence hibernate_sequence start 1 increment 1
2017-09-06 15:41:44.148 ERROR 13787 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : ERROR: relation "hibernate_sequence" already exists
Hibernate: create table person (id int8 not null, additional_data jsonb, first_name varchar(255), last_name varchar(255), primary key (id))
2017-09-06 15:41:44.157  INFO 13787 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000230: Schema export complete
2017-09-06 15:41:44.186  INFO 13787 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2017-09-06 15:41:44.458  INFO 13787 --- [           main] .v.JsonbHibernateExampleApplicationTests : Started JsonbHibernateExampleApplicationTests in 2.032 seconds (JVM running for 2.545)
2017-09-06 15:41:44.511  INFO 13787 --- [           main] o.h.h.i.QueryTranslatorFactoryInitiator  : HHH000397: Using ASTQueryTranslatorFactory
Hibernate: select person0_.id as id1_0_, person0_.additional_data as addition2_0_, person0_.first_name as first_na3_0_, person0_.last_name as last_nam4_0_ from person person0_
Hibernate: select nextval ('hibernate_sequence')
2017-09-06 15:41:44.614  WARN 13787 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 42501
2017-09-06 15:41:44.614 ERROR 13787 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: permission denied for sequence hibernate_sequence
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.279 sec <<< FAILURE! - in com.vojtechruzicka.JsonbHibernateExampleApplicationTests
contextLoads(com.vojtechruzicka.JsonbHibernateExampleApplicationTests)  Time elapsed: 0.162 sec  <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:70)
        at org.hibernate.id.SequenceGenerator.generateHolder(SequenceGenerator.java:116)
        at org.hibernate.id.SequenceGenerator.generate(SequenceGenerator.java:109)
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:101)
        at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:775)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:748)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:753)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1146)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298)
        at com.sun.proxy.$Proxy65.persist(Unknown Source)
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:508)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:489)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy67.save(Unknown Source)
        at com.vojtechruzicka.JsonbHibernateExampleApplicationTests.contextLoads(JsonbHibernateExampleApplicationTests.java:35)

2017-09-06 15:41:44.631  INFO 13787 --- [       Thread-3] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7133da86: startup date [Wed Sep 06 15:41:42 GMT 2017]; root of context hierarchy
2017-09-06 15:41:44.633  INFO 13787 --- [       Thread-3] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'

Results :

Tests in error: 
  JsonbHibernateExampleApplicationTests.contextLoads:35 » InvalidDataAccessResourceUsage

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------

```

**Comment by vojtechruz** [comment]
Hi, thank you for the report and sorry for the delay. Good idea with the automatic DB creation, I've updated  the app to include automatic generation out of the box. It looks like the app is trying to drop the DB on start. Specifically, it is trying to drop the sequence, but the app is not an owner of it, so the access is denied. Did you create the sequence manually under different privileges?

2017-09-06 15:41:44.147 ERROR 13787 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000389: Unsuccessful: drop sequence hibernate_sequence
2017-09-06 15:41:44.147 ERROR 13787 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : ERROR: must be owner of relation hibernate_sequence
